-- Target database initialization

-- Create sync monitoring table
CREATE TABLE IF NOT EXISTS sync_log (
    id SERIAL PRIMARY KEY,
    connector_name VARCHAR(100),
    operation_type VARCHAR(20),
    records_processed INTEGER,
    status VARCHAR(50),
    error_message TEXT,
    timestamp TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Insert initial log entry
INSERT INTO sync_log (connector_name, operation_type, records_processed, status)
VALUES ('jdbc-sink-all-tables', 'INITIALIZATION', 0, 'READY');

-- Drop tables if exists for clean setup
DROP TABLE IF EXISTS public.inventory CASCADE;
DROP TABLE IF EXISTS public.productitem CASCADE;

-- ===========================================
-- INVENTORY TABLE
-- ===========================================
CREATE TABLE public.inventory (
    id BIGSERIAL PRIMARY KEY,
    inventoryid BIGINT NOT NULL UNIQUE,
    
    currentcost FLOAT8 NULL,
    expirydate DATE NULL,
    frombin INT4 NULL,
    fromlocation INT4 NULL,
    fromspeciallocation INT4 NULL,
    incomingmode INT4 NULL,
    lastcost FLOAT8 NULL,
    list FLOAT8 NULL,
    lpprice FLOAT8 NULL,
    lppricecurrency INT4 NULL,
    movementdate DATE NULL,
    nfbrsp FLOAT8 NULL,
    outgoingmode INT4 NULL,
    productitem BIGINT NULL,
    quantity BIGINT NULL,
    reserveprice1 FLOAT8 NULL,
    reserveprice2 FLOAT8 NULL,
    reserveprice3 FLOAT8 NULL,
    retailsalesprice FLOAT8 NULL,
    tobin INT4 NULL,
    tolocation INT4 NULL,
    tospeciallocation INT4 NULL,
    transactioncode VARCHAR NULL,
    transactionnumber VARCHAR NULL,
    doc_number VARCHAR NULL,
    doc_type INT4 NULL,
    remark VARCHAR NULL,
    customer INT4 DEFAULT 0 NULL,
    purpose INT4 DEFAULT 0 NULL,
    purposestatus INT4 DEFAULT 0 NULL,
    intransit INT4 DEFAULT 0 NULL,
    purposedocument VARCHAR NULL,
    offline INT4 DEFAULT 0 NULL,
    reserveinventory INT4 DEFAULT 0 NULL,
    organisation_id INT4 DEFAULT 1 NULL,
    createdatetime TIMESTAMP DEFAULT NOW() NULL,
    local_device_pk INT4 NULL,
    data_version INT4 NULL
);

CREATE INDEX idx_inventory_inventoryid ON public.inventory(inventoryid);
GRANT ALL PRIVILEGES ON TABLE public.inventory TO integration_user;
GRANT USAGE, SELECT ON SEQUENCE public.inventory_id_seq TO integration_user;

-- ===========================================
-- PRODUCTITEM TABLE
-- ===========================================
CREATE TABLE public.productitem (
    id BIGSERIAL PRIMARY KEY,
    productitemid INT4 NOT NULL UNIQUE,
    
    bddiscount FLOAT8 NULL,
    ccchangeby INT4 NULL,
    ccchangedate DATE NULL,
    cceffectivedate DATE NULL,
    createdatetime TIMESTAMP NULL,
    currentcost FLOAT8 NULL,
    deletestatus INT4 NULL,
    exchangerate FLOAT8 NULL,
    floordiscount FLOAT8 NULL,
    focitem INT4 NULL,
    lastcost FLOAT8 NULL,
    lasteditdatetime TIMESTAMP NULL,
    lcchangeby INT4 NULL,
    lcchangedate DATE NULL,
    lceffectivedate DATE NULL,
    list FLOAT8 NULL,
    listchangeby INT4 NULL,
    listchangedate DATE NULL,
    listeffectivedate DATE NULL,
    lpprice FLOAT8 NULL,
    lppricechangeby INT4 NULL,
    lppricechangedate DATE NULL,
    lppricecurrency INT4 NULL,
    lppriceeffectivedate DATE NULL,
    minorderqty INT8 NULL,
    minqty INT8 NULL,
    nfbchangeby INT4 NULL,
    nfbchangedate DATE NULL,
    nfbeffectivedate DATE NULL,
    nfbrsp FLOAT8 NULL,
    normaldiscount FLOAT8 NULL,
    productbrand INT4 NULL,
    productcategory INT4 NULL,
    productcode VARCHAR NULL,
    productgroup INT4 NULL,
    productitembarcode VARCHAR NULL,
    productitemdesc VARCHAR NULL,
    productlaunchdate DATE NULL,
    productskunumber VARCHAR NULL,
    producttype INT4 DEFAULT 0 NULL,
    rchangeby1 INT4 NULL,
    rchangeby2 INT4 NULL,
    rchangeby3 INT4 NULL,
    rchangedate1 DATE NULL,
    rchangedate2 DATE NULL,
    rchangedate3 DATE NULL,
    reffectivedate1 DATE NULL,
    reffectivedate2 DATE NULL,
    reffectivedate3 DATE NULL,
    remark VARCHAR NULL,
    reorderqty INT8 DEFAULT 0 NULL,
    reserveprice1 FLOAT8 NULL,
    reserveprice2 FLOAT8 NULL,
    reserveprice3 FLOAT8 NULL,
    retailsalesprice FLOAT8 NULL,
    rspchangeby INT4 NULL,
    rspchangedate DATE NULL,
    rspeffectivedate DATE NULL,
    staffdiscount FLOAT8 NULL,
    status INT4 NULL,
    supplier INT4 NULL,
    supplieritemcode VARCHAR NULL,
    supplierpacksize INT4 NULL,
    unitofmeasurement INT4 NULL,
    vipdiscount FLOAT8 NULL,
    waclearingcost FLOAT8 NULL,
    wacommissioncost FLOAT8 NULL,
    wacustomdutycost FLOAT8 NULL,
    wafreightcost FLOAT8 NULL,
    wainsurancecost FLOAT8 NULL,
    wainvoicecost FLOAT8 NULL,
    waothercost FLOAT8 NULL,
    wapackingcost FLOAT8 NULL,
    color VARCHAR NULL,
    sex VARCHAR NULL,
    size VARCHAR NULL,
    productseason VARCHAR NULL,
    uomid INT4 NULL,
    producttype2 INT4 NULL,
    discountpolicy INT4 NULL,
    colourid INT4 NULL,
    sizeid INT4 NULL,
    productdiscountgroup INT4 NULL,
    expirydate DATE NULL,
    serialno VARCHAR NULL,
    weblink VARCHAR NULL,
    pricingpolicy INT4 NULL,
    supplieritemcode2 VARCHAR NULL,
    supplieritemcode3 VARCHAR NULL,
    supplieritemcode4 VARCHAR NULL,
    supplieritemcode5 VARCHAR NULL,
    supplieritemcode6 VARCHAR NULL,
    retailsalesprice2 FLOAT4 NULL,
    retailsalesprice3 FLOAT4 NULL,
    retailsalesprice4 FLOAT4 NULL,
    retailsalesprice5 FLOAT4 NULL,
    floorprice FLOAT8 NULL,
    kitchenorder VARCHAR NULL,
    width VARCHAR NULL,
    height VARCHAR NULL,
    depth VARCHAR NULL,
    imageext VARCHAR NULL,
    lastimageupdate TIMESTAMP NULL,
    rspoint FLOAT8 DEFAULT 0 NULL,
    customerpoint FLOAT8 DEFAULT 0 NULL,
    display INT4 DEFAULT 0 NULL,
    weight FLOAT8 NULL,
    goldtype INT4 NULL,
    tagno VARCHAR NULL,
    stonetype VARCHAR NULL,
    datein DATE NULL,
    subcategory VARCHAR NULL,
    subcategory2 VARCHAR NULL,
    grnnumber VARCHAR NULL,
    stoneqty FLOAT8 DEFAULT 0 NULL,
    stoneweight VARCHAR NULL,
    stonecolor VARCHAR NULL,
    stoneclarity VARCHAR NULL,
    stonecut VARCHAR NULL,
    ratetype INT4 NULL,
    stonetype2 VARCHAR NULL,
    stoneqty2 FLOAT8 NULL,
    stoneweight2 VARCHAR NULL,
    stonecolor2 VARCHAR NULL,
    stoneclarity2 VARCHAR NULL,
    stonecut2 VARCHAR NULL,
    style VARCHAR NULL,
    hasserial BOOL DEFAULT false NULL,
    systempoint INT4 DEFAULT 0 NULL,
    productstyle INT4 NULL,
    field1 VARCHAR NULL,
    field2 VARCHAR NULL,
    field3 VARCHAR NULL,
    field4 VARCHAR NULL,
    field5 VARCHAR NULL,
    field6 VARCHAR NULL,
    field7 VARCHAR NULL,
    field8 VARCHAR NULL,
    field9 VARCHAR NULL,
    field10 VARCHAR NULL,
    productpoint FLOAT8 NULL,
    redemptionpoint FLOAT8 DEFAULT 0 NULL,
    printcollection INT4 DEFAULT 0 NULL,
    editprice INT4 DEFAULT 0 NULL,
    modifierids VARCHAR(255) NULL,
    itemtaxpct FLOAT8 NULL,
    productitemdesclong VARCHAR NULL,
    sizegroup VARCHAR(255) NULL,
    company INT4 DEFAULT 0 NULL,
    printlabel INT4 DEFAULT 0 NULL,
    matrixid INT4 DEFAULT 0 NULL,
    isdisplay INT4 DEFAULT 1 NULL,
    volumetricweight FLOAT8 NULL,
    warrantyperiod INT4 NULL,
    taxgroup INT4 DEFAULT -1 NOT NULL,
    pricewithouttax FLOAT8 NULL,
    sizechartid INT4 DEFAULT 0 NULL,
    isgiftcard BOOL DEFAULT false NULL,
    hasbatch INT4 DEFAULT 0 NULL,
    productitemdeschtml VARCHAR NULL,
    seasonid INT4 DEFAULT -1 NULL,
    product_brand_l3_id INT4 DEFAULT -1 NULL,
    product_brand_l2_id INT4 DEFAULT -1 NULL,
    product_category_l2_id INT4 DEFAULT -1 NULL,
    product_category_l3_id INT4 DEFAULT -1 NULL,
    isrecurring BOOL DEFAULT false NULL,
    recurringperiod INT4 DEFAULT 0 NULL,
    customflag INT4 NULL,
    expdays INT4 DEFAULT -1 NULL,
    genderid INT4 NULL,
    organisation_id INT4 DEFAULT 0 NULL,
    foreignrsp1 FLOAT8 DEFAULT 0 NULL,
    foreignrsp2 FLOAT8 DEFAULT 0 NULL,
    foreignrsp3 FLOAT8 DEFAULT 0 NULL,
    foreignrsp4 FLOAT8 DEFAULT 0 NULL,
    foreignrsp5 FLOAT8 DEFAULT 0 NULL,
    foreignrsp6 FLOAT8 DEFAULT 0 NULL,
    foreignrsp7 FLOAT8 DEFAULT 0 NULL,
    foreignrsp8 FLOAT8 DEFAULT 0 NULL,
    foreignrsp9 FLOAT8 DEFAULT 0 NULL,
    foreignrsp10 FLOAT8 DEFAULT 0 NULL,
    url_alias VARCHAR NULL,
    meta_title VARCHAR NULL,
    meta_keyword VARCHAR NULL,
    meta_description VARCHAR NULL,
    prelaunch_date DATE NULL,
    prelaunch_custype VARCHAR NULL,
    field11 VARCHAR NULL,
    field12 VARCHAR NULL,
    field13 VARCHAR NULL,
    field14 VARCHAR NULL,
    field15 VARCHAR NULL,
    field16 VARCHAR NULL,
    field17 VARCHAR NULL,
    field18 VARCHAR NULL,
    field19 VARCHAR NULL,
    field20 VARCHAR NULL,
    is_soldout INT4 DEFAULT 0 NULL,
    productlaunch_datetime TIMESTAMPTZ NULL,
    prelaunch_datetime TIMESTAMPTZ NULL,
    prelaunch_condition INT4 NULL,
    prelaunch_enddatetime TIMESTAMPTZ NULL,
    is_system BOOL DEFAULT false NULL,
    product_local_type INT4 DEFAULT 1 NULL,
    expense_id INT4 DEFAULT -1 NULL,
    time_charge_session_duration INT4 DEFAULT 0 NULL,
    time_charge_allow_buffer_time INT4 DEFAULT 0 NULL,
    time_charge_buffer_time INT4 DEFAULT 0 NULL,
    have_additional_remarks INT4 DEFAULT 0 NULL,
    time_charge_is_overtime_charge INT4 DEFAULT 0 NULL,
    time_charge_is_overtime_minutes INT4 DEFAULT 0 NULL,
    time_charge_is_overtime_value FLOAT8 DEFAULT 0 NULL,
    product_tax_type INT4 DEFAULT 0 NULL,
    is_service_charge INT4 DEFAULT 0 NULL,
    sync_product_status INT4 DEFAULT 1 NULL,
    sync_api_id INT4 DEFAULT 0 NULL,
    uomproducttype INT4 NULL,
    baseproduct INT4 NULL,
    billofmaterialid INT4 NULL,
    measurementtype INT4 NULL,
    is_carton BOOL DEFAULT false NULL,
    carton_type INT4 DEFAULT -1 NULL,
    is_sellable BOOL DEFAULT true NULL,
    carton_matrix_id INT4 DEFAULT -1 NULL,
    carton_isused INT4 DEFAULT 1 NULL,
    foreigncost1 FLOAT8 DEFAULT 0 NULL,
    foreigncost2 FLOAT8 DEFAULT 0 NULL,
    foreigncost3 FLOAT8 DEFAULT 0 NULL,
    foreigncost4 FLOAT8 DEFAULT 0 NULL,
    foreigncost5 FLOAT8 DEFAULT 0 NULL,
    foreigncost6 FLOAT8 DEFAULT 0 NULL,
    foreigncost7 FLOAT8 DEFAULT 0 NULL,
    foreigncost8 FLOAT8 DEFAULT 0 NULL,
    foreigncost9 FLOAT8 DEFAULT 0 NULL,
    foreigncost10 FLOAT8 DEFAULT 0 NULL,
    hide_price_for_ec INT4 DEFAULT 0 NULL,
    is_shown_in_ec_active_menu INT4 DEFAULT 0 NULL,
    product_commission_amount FLOAT8 NULL,
    product_commission_type INT4 DEFAULT 2 NULL,
    dummy_retailsalesprice FLOAT8 NULL,
    electronic_label_display_price FLOAT8 NULL,
    sync_time_from_thirdparty TIMESTAMP NULL,
    meta_thumbnail VARCHAR NULL,
    applicable_taxtype INT4 NULL,
    supplier_lead_time_days INT4 NULL,
    supplier_currency VARCHAR NULL,
    supplier_cost FLOAT8 NULL,
    supplier_launch_date TIMESTAMPTZ NULL,
    maxorderqty INT8 NULL,
    api_create_hash VARCHAR NULL,
    ip_code_id INT8 NULL,
    royalty_classification_id INT8 NULL,
    rsp_at_creation FLOAT8 NULL,
    item_rounding_mode INT4 DEFAULT -1 NULL,
    item_rounding_enabled BOOL DEFAULT false NULL,
    adjust_price_with_foreign_currency BOOL DEFAULT false NULL,
    foreignrsp1_currency VARCHAR NULL,
    controlleditem_id INT4 DEFAULT -1 NULL
);

CREATE INDEX idx_productitem_productitemid ON public.productitem(productitemid);
GRANT ALL PRIVILEGES ON TABLE public.productitem TO integration_user;
GRANT USAGE, SELECT ON SEQUENCE public.productitem_id_seq TO integration_user;

-- Display confirmation
SELECT 'Target database initialized successfully!' AS status;
SELECT 'Table inventory created with ' || COUNT(*) || ' columns' AS info FROM information_schema.columns WHERE table_name = 'inventory';
SELECT 'Table productitem created with ' || COUNT(*) || ' columns' AS info FROM information_schema.columns WHERE table_name = 'productitem';